cache:
    - C:\Strawberry -> .appveyor_clear_cache.txt

shallow_clone: true

install:
  - if not exist "C:\Strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_SLUG%
  - cpanm --installdeps . || type C:\Users\appveyor\.cpanm\build.log ; perl -e "exit 1"

build_script:
  - perl Makefile.PL || type C:\Users\appveyor\.cpanm\build.log ; perl -e "exit 1"
  - gmake || type C:\Users\appveyor\.cpanm\build.log ; perl -e "exit 1"
  - gmake test || type C:\Users\appveyor\.cpanm\build.log ; perl -e "exit 1"
