---
abstract: 'Scoped checks for object leaks'
author:
  - 'Andy Armstrong <andy@hexten.net>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-LeakGuard-Object
provides:
  Devel::LeakGuard::Object:
    file: lib/Devel/LeakGuard/Object.pm
    version: '0.07'
  Devel::LeakGuard::Object::State:
    file: lib/Devel/LeakGuard/Object/State.pm
    version: '0.07'
requires:
  List::Util: '1.19'
  Scalar::Util: '1.19'
  Test::Differences: '0'
  Test::More: '0.42'
  latest: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Devel-LeakGuard-Object
  license: http://dev.perl.org/licenses/
  repository: 'git://github.com/shlomif/Devel--LeakGuard--Object.git (fetch)'
version: '0.07'
