--- 
abstract: "Detect leaks of objects "
author: 
  - Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-LeakTrack-Object
no_index: 
  directory: 
    - inc
    - t
requires: 
  Scalar::Util: 1.19
  perl: 5.005
version: 0.1

