---
name: Devel-LeakGuard-Object
version: 0.06
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Scoped checks for object leaks
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Devel-LeakGuard-Object
  license: http://dev.perl.org/licenses/
  repository: git://github.com/AndyA/Devel--LeakGuard--Object.git
requires:
  List::Util: 1.19
  Scalar::Util: 1.19
  Test::Differences: 0
  Test::More: 0.42
  latest: 0
provides:
  Devel::LeakGuard::Object:
    file: lib/Devel/LeakGuard/Object.pm
    version: 0.06
  Devel::LeakGuard::Object::State:
    file: lib/Devel/LeakGuard/Object/State.pm
    version: 0.06
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
